"""billing invoices customers payments

Revision ID: 37881c725ac7
Revises: ea30328fb7b9
Create Date: 2026-09-25 01:21:45.283338

"""

from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "37881c725ac7"
down_revision: str | Sequence[str] | None = "ea30328fb7b9"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "customer",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("phone", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("email", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("gstin", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("state", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("address", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("created_at", sqlmodel.sql.sqltypes.UTCDateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("customer", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_customer_name"), ["name"], unique=False)
        batch_op.create_index(batch_op.f("ix_customer_phone"), ["phone"], unique=False)

    op.create_table(
        "invoice",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("number", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("kind", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("customer_id", sa.Integer(), nullable=True),
        sa.Column("customer_name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("customer_phone", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("customer_gstin", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("customer_address", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("place_of_supply", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("warehouse_id", sa.Integer(), nullable=True),
        sa.Column("status", sa.Enum("PAID", "PARTIAL", "UNPAID", "CANCELLED", name="invoicestatus"), nullable=False),
        sa.Column("payment_mode", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("prices_include_gst", sa.Boolean(), nullable=False),
        sa.Column("subtotal", sa.Float(), nullable=False),
        sa.Column("discount", sa.Float(), nullable=False),
        sa.Column("taxable", sa.Float(), nullable=False),
        sa.Column("cgst", sa.Float(), nullable=False),
        sa.Column("sgst", sa.Float(), nullable=False),
        sa.Column("igst", sa.Float(), nullable=False),
        sa.Column("tax", sa.Float(), nullable=False),
        sa.Column("round_off", sa.Float(), nullable=False),
        sa.Column("total", sa.Float(), nullable=False),
        sa.Column("amount_paid", sa.Float(), nullable=False),
        sa.Column("notes", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("created_by", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("created_at", sqlmodel.sql.sqltypes.UTCDateTime(), nullable=False),
        sa.Column("cancelled_at", sqlmodel.sql.sqltypes.UTCDateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["customer_id"],
            ["customer.id"],
        ),
        sa.ForeignKeyConstraint(
            ["warehouse_id"],
            ["warehouse.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("invoice", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_invoice_created_at"), ["created_at"], unique=False)
        batch_op.create_index(batch_op.f("ix_invoice_customer_id"), ["customer_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_invoice_number"), ["number"], unique=True)
        batch_op.create_index(batch_op.f("ix_invoice_status"), ["status"], unique=False)

    op.create_table(
        "invoiceline",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("invoice_id", sa.Integer(), nullable=False),
        sa.Column("product_id", sa.Integer(), nullable=False),
        sa.Column("warehouse_id", sa.Integer(), nullable=False),
        sa.Column("sku", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("hsn_code", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("quantity", sa.Integer(), nullable=False),
        sa.Column("unit_price", sa.Float(), nullable=False),
        sa.Column("discount_pct", sa.Float(), nullable=False),
        sa.Column("gst_rate", sa.Float(), nullable=False),
        sa.Column("taxable", sa.Float(), nullable=False),
        sa.Column("tax", sa.Float(), nullable=False),
        sa.Column("total", sa.Float(), nullable=False),
        sa.ForeignKeyConstraint(
            ["invoice_id"],
            ["invoice.id"],
        ),
        sa.ForeignKeyConstraint(
            ["product_id"],
            ["product.id"],
        ),
        sa.ForeignKeyConstraint(
            ["warehouse_id"],
            ["warehouse.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("invoiceline", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_invoiceline_invoice_id"), ["invoice_id"], unique=False)

    op.create_table(
        "payment",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("invoice_id", sa.Integer(), nullable=False),
        sa.Column("amount", sa.Float(), nullable=False),
        sa.Column("mode", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("reference", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("created_by", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("created_at", sqlmodel.sql.sqltypes.UTCDateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["invoice_id"],
            ["invoice.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("payment", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_payment_invoice_id"), ["invoice_id"], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("payment", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_payment_invoice_id"))

    op.drop_table("payment")
    with op.batch_alter_table("invoiceline", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_invoiceline_invoice_id"))

    op.drop_table("invoiceline")
    with op.batch_alter_table("invoice", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_invoice_status"))
        batch_op.drop_index(batch_op.f("ix_invoice_number"))
        batch_op.drop_index(batch_op.f("ix_invoice_customer_id"))
        batch_op.drop_index(batch_op.f("ix_invoice_created_at"))

    op.drop_table("invoice")
    with op.batch_alter_table("customer", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_customer_phone"))
        batch_op.drop_index(batch_op.f("ix_customer_name"))

    op.drop_table("customer")
    # ### end Alembic commands ###
