"""product barcode unit expiry

Revision ID: 3e0209a6ffb4
Revises: 37881c725ac7
Create Date: 2026-09-25 07:15:00.854005

"""

from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "3e0209a6ffb4"
down_revision: str | Sequence[str] | None = "37881c725ac7"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("product", schema=None) as batch_op:
        batch_op.add_column(sa.Column("barcode", sqlmodel.sql.sqltypes.AutoString(), nullable=True))
        batch_op.add_column(sa.Column("unit", sqlmodel.sql.sqltypes.AutoString(), nullable=False, server_default="pcs"))
        batch_op.add_column(sa.Column("expiry_date", sa.Date(), nullable=True))
        batch_op.create_index(batch_op.f("ix_product_barcode"), ["barcode"], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("product", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_product_barcode"))
        batch_op.drop_column("expiry_date")
        batch_op.drop_column("unit")
        batch_op.drop_column("barcode")

    # ### end Alembic commands ###
