"""initial schema

Revision ID: 9bfd7954321a
Revises:
Create Date: 2026-09-24 16:11:22.744731

"""

from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "9bfd7954321a"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "agenttrace",
        sa.Column("id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("conversation_id", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("agent", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("provider", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("model", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("trigger", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("input", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("output", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("status", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("steps", sa.JSON(), nullable=True),
        sa.Column("input_tokens", sa.Integer(), nullable=False),
        sa.Column("output_tokens", sa.Integer(), nullable=False),
        sa.Column("duration_ms", sa.Integer(), nullable=False),
        sa.Column("created_at", sqlmodel.sql.sqltypes.UTCDateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("agenttrace", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_agenttrace_conversation_id"), ["conversation_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_agenttrace_created_at"), ["created_at"], unique=False)

    op.create_table(
        "approvalrequest",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("conversation_id", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("agent", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("tool", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("args", sa.JSON(), nullable=True),
        sa.Column("reason", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("status", sa.Enum("PENDING", "APPROVED", "REJECTED", "FAILED", name="approvalstatus"), nullable=False),
        sa.Column("result", sa.JSON(), nullable=True),
        sa.Column("created_at", sqlmodel.sql.sqltypes.UTCDateTime(), nullable=False),
        sa.Column("decided_at", sqlmodel.sql.sqltypes.UTCDateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("approvalrequest", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_approvalrequest_conversation_id"), ["conversation_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_approvalrequest_status"), ["status"], unique=False)

    op.create_table(
        "category",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("color", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("category", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_category_name"), ["name"], unique=True)

    op.create_table(
        "conversation",
        sa.Column("id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("title", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("agent", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("provider", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("messages", sa.JSON(), nullable=True),
        sa.Column("display", sa.JSON(), nullable=True),
        sa.Column("created_at", sqlmodel.sql.sqltypes.UTCDateTime(), nullable=False),
        sa.Column("updated_at", sqlmodel.sql.sqltypes.UTCDateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("conversation", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_conversation_updated_at"), ["updated_at"], unique=False)

    op.create_table(
        "eventlog",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("type", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("source", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("payload", sa.JSON(), nullable=True),
        sa.Column("created_at", sqlmodel.sql.sqltypes.UTCDateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("eventlog", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_eventlog_created_at"), ["created_at"], unique=False)
        batch_op.create_index(batch_op.f("ix_eventlog_type"), ["type"], unique=False)

    op.create_table(
        "report",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("kind", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("title", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("content", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("created_by", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("created_at", sqlmodel.sql.sqltypes.UTCDateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("report", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_report_created_at"), ["created_at"], unique=False)
        batch_op.create_index(batch_op.f("ix_report_kind"), ["kind"], unique=False)

    op.create_table(
        "setting",
        sa.Column("key", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("value", sa.JSON(), nullable=True),
        sa.PrimaryKeyConstraint("key"),
    )
    op.create_table(
        "supplier",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("email", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("phone", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("lead_time_days", sa.Integer(), nullable=False),
        sa.Column("rating", sa.Float(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("supplier", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_supplier_name"), ["name"], unique=False)

    op.create_table(
        "user",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("email", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("role", sa.Enum("ADMIN", "MANAGER", "STAFF", "VIEWER", name="role"), nullable=False),
        sa.Column("password_hash", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("created_at", sqlmodel.sql.sqltypes.UTCDateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("user", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_user_email"), ["email"], unique=True)

    op.create_table(
        "warehouse",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("code", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("location", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("warehouse", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_warehouse_code"), ["code"], unique=True)

    op.create_table(
        "webhook",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("url", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("events", sa.JSON(), nullable=True),
        sa.Column("secret", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.Column("last_status", sa.Integer(), nullable=True),
        sa.Column("last_error", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("last_delivery_at", sqlmodel.sql.sqltypes.UTCDateTime(), nullable=True),
        sa.Column("created_at", sqlmodel.sql.sqltypes.UTCDateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "cyclecount",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("number", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("warehouse_id", sa.Integer(), nullable=False),
        sa.Column("scope", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("status", sa.Enum("OPEN", "POSTED", "CANCELLED", name="countstatus"), nullable=False),
        sa.Column("created_by", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("created_at", sqlmodel.sql.sqltypes.UTCDateTime(), nullable=False),
        sa.Column("posted_at", sqlmodel.sql.sqltypes.UTCDateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["warehouse_id"],
            ["warehouse.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("cyclecount", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_cyclecount_number"), ["number"], unique=True)
        batch_op.create_index(batch_op.f("ix_cyclecount_status"), ["status"], unique=False)

    op.create_table(
        "product",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("sku", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("description", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("category_id", sa.Integer(), nullable=True),
        sa.Column("supplier_id", sa.Integer(), nullable=True),
        sa.Column("unit_cost", sa.Float(), nullable=False),
        sa.Column("unit_price", sa.Float(), nullable=False),
        sa.Column("reorder_point", sa.Integer(), nullable=True),
        sa.Column("safety_stock", sa.Integer(), nullable=True),
        sa.Column("min_order_qty", sa.Integer(), nullable=False),
        sa.Column("lead_time_days", sa.Integer(), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("created_at", sqlmodel.sql.sqltypes.UTCDateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["category_id"],
            ["category.id"],
        ),
        sa.ForeignKeyConstraint(
            ["supplier_id"],
            ["supplier.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("product", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_product_name"), ["name"], unique=False)
        batch_op.create_index(batch_op.f("ix_product_sku"), ["sku"], unique=True)

    op.create_table(
        "purchaseorder",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("number", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("supplier_id", sa.Integer(), nullable=False),
        sa.Column("warehouse_id", sa.Integer(), nullable=False),
        sa.Column("status", sa.Enum("DRAFT", "APPROVED", "ORDERED", "RECEIVED", "CANCELLED", name="postatus"), nullable=False),
        sa.Column("created_by", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("notes", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("created_at", sqlmodel.sql.sqltypes.UTCDateTime(), nullable=False),
        sa.Column("expected_at", sqlmodel.sql.sqltypes.UTCDateTime(), nullable=True),
        sa.Column("received_at", sqlmodel.sql.sqltypes.UTCDateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["supplier_id"],
            ["supplier.id"],
        ),
        sa.ForeignKeyConstraint(
            ["warehouse_id"],
            ["warehouse.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("purchaseorder", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_purchaseorder_number"), ["number"], unique=True)
        batch_op.create_index(batch_op.f("ix_purchaseorder_status"), ["status"], unique=False)

    op.create_table(
        "webhookdelivery",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("webhook_id", sa.Integer(), nullable=False),
        sa.Column("event_type", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("status_code", sa.Integer(), nullable=True),
        sa.Column("success", sa.Boolean(), nullable=False),
        sa.Column("attempts", sa.Integer(), nullable=False),
        sa.Column("error", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("duration_ms", sa.Integer(), nullable=False),
        sa.Column("created_at", sqlmodel.sql.sqltypes.UTCDateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["webhook_id"],
            ["webhook.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("webhookdelivery", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_webhookdelivery_created_at"), ["created_at"], unique=False)
        batch_op.create_index(batch_op.f("ix_webhookdelivery_webhook_id"), ["webhook_id"], unique=False)

    op.create_table(
        "alert",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("kind", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("severity", sa.Enum("INFO", "WARNING", "CRITICAL", name="alertseverity"), nullable=False),
        sa.Column("product_id", sa.Integer(), nullable=True),
        sa.Column("message", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("resolved", sa.Boolean(), nullable=False),
        sa.Column("created_at", sqlmodel.sql.sqltypes.UTCDateTime(), nullable=False),
        sa.Column("resolved_at", sqlmodel.sql.sqltypes.UTCDateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["product_id"],
            ["product.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("alert", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_alert_kind"), ["kind"], unique=False)
        batch_op.create_index(batch_op.f("ix_alert_resolved"), ["resolved"], unique=False)

    op.create_table(
        "cyclecountline",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("count_id", sa.Integer(), nullable=False),
        sa.Column("product_id", sa.Integer(), nullable=False),
        sa.Column("expected", sa.Integer(), nullable=False),
        sa.Column("counted", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["count_id"],
            ["cyclecount.id"],
        ),
        sa.ForeignKeyConstraint(
            ["product_id"],
            ["product.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("cyclecountline", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_cyclecountline_count_id"), ["count_id"], unique=False)

    op.create_table(
        "purchaseorderline",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("order_id", sa.Integer(), nullable=False),
        sa.Column("product_id", sa.Integer(), nullable=False),
        sa.Column("quantity", sa.Integer(), nullable=False),
        sa.Column("unit_cost", sa.Float(), nullable=False),
        sa.ForeignKeyConstraint(
            ["order_id"],
            ["purchaseorder.id"],
        ),
        sa.ForeignKeyConstraint(
            ["product_id"],
            ["product.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("purchaseorderline", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_purchaseorderline_order_id"), ["order_id"], unique=False)

    op.create_table(
        "stocklevel",
        sa.Column("product_id", sa.Integer(), nullable=False),
        sa.Column("warehouse_id", sa.Integer(), nullable=False),
        sa.Column("quantity", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["product_id"],
            ["product.id"],
        ),
        sa.ForeignKeyConstraint(
            ["warehouse_id"],
            ["warehouse.id"],
        ),
        sa.PrimaryKeyConstraint("product_id", "warehouse_id"),
    )
    op.create_table(
        "stockmovement",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("product_id", sa.Integer(), nullable=False),
        sa.Column("warehouse_id", sa.Integer(), nullable=False),
        sa.Column(
            "type",
            sa.Enum("RECEIPT", "SALE", "ADJUSTMENT", "TRANSFER_IN", "TRANSFER_OUT", "RETURN", name="movementtype"),
            nullable=False,
        ),
        sa.Column("quantity", sa.Integer(), nullable=False),
        sa.Column("reference", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("note", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("actor", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("created_at", sqlmodel.sql.sqltypes.UTCDateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["product_id"],
            ["product.id"],
        ),
        sa.ForeignKeyConstraint(
            ["warehouse_id"],
            ["warehouse.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("stockmovement", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_stockmovement_created_at"), ["created_at"], unique=False)
        batch_op.create_index(batch_op.f("ix_stockmovement_product_id"), ["product_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_stockmovement_type"), ["type"], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("stockmovement", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_stockmovement_type"))
        batch_op.drop_index(batch_op.f("ix_stockmovement_product_id"))
        batch_op.drop_index(batch_op.f("ix_stockmovement_created_at"))

    op.drop_table("stockmovement")
    op.drop_table("stocklevel")
    with op.batch_alter_table("purchaseorderline", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_purchaseorderline_order_id"))

    op.drop_table("purchaseorderline")
    with op.batch_alter_table("cyclecountline", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_cyclecountline_count_id"))

    op.drop_table("cyclecountline")
    with op.batch_alter_table("alert", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_alert_resolved"))
        batch_op.drop_index(batch_op.f("ix_alert_kind"))

    op.drop_table("alert")
    with op.batch_alter_table("webhookdelivery", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_webhookdelivery_webhook_id"))
        batch_op.drop_index(batch_op.f("ix_webhookdelivery_created_at"))

    op.drop_table("webhookdelivery")
    with op.batch_alter_table("purchaseorder", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_purchaseorder_status"))
        batch_op.drop_index(batch_op.f("ix_purchaseorder_number"))

    op.drop_table("purchaseorder")
    with op.batch_alter_table("product", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_product_sku"))
        batch_op.drop_index(batch_op.f("ix_product_name"))

    op.drop_table("product")
    with op.batch_alter_table("cyclecount", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_cyclecount_status"))
        batch_op.drop_index(batch_op.f("ix_cyclecount_number"))

    op.drop_table("cyclecount")
    op.drop_table("webhook")
    with op.batch_alter_table("warehouse", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_warehouse_code"))

    op.drop_table("warehouse")
    with op.batch_alter_table("user", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_user_email"))

    op.drop_table("user")
    with op.batch_alter_table("supplier", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_supplier_name"))

    op.drop_table("supplier")
    op.drop_table("setting")
    with op.batch_alter_table("report", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_report_kind"))
        batch_op.drop_index(batch_op.f("ix_report_created_at"))

    op.drop_table("report")
    with op.batch_alter_table("eventlog", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_eventlog_type"))
        batch_op.drop_index(batch_op.f("ix_eventlog_created_at"))

    op.drop_table("eventlog")
    with op.batch_alter_table("conversation", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_conversation_updated_at"))

    op.drop_table("conversation")
    with op.batch_alter_table("category", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_category_name"))

    op.drop_table("category")
    with op.batch_alter_table("approvalrequest", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_approvalrequest_status"))
        batch_op.drop_index(batch_op.f("ix_approvalrequest_conversation_id"))

    op.drop_table("approvalrequest")
    with op.batch_alter_table("agenttrace", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_agenttrace_created_at"))
        batch_op.drop_index(batch_op.f("ix_agenttrace_conversation_id"))

    op.drop_table("agenttrace")
    # ### end Alembic commands ###
