"""returns payables loyalty

Revision ID: adbe5fafdf72
Revises: 3e0209a6ffb4
Create Date: 2026-09-25 08:46:41.333730

"""

from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "adbe5fafdf72"
down_revision: str | Sequence[str] | None = "3e0209a6ffb4"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "supplierpayment",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("supplier_id", sa.Integer(), nullable=False),
        sa.Column("amount", sa.Float(), nullable=False),
        sa.Column("mode", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("reference", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("created_by", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("created_at", sqlmodel.sql.sqltypes.UTCDateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["supplier_id"],
            ["supplier.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("supplierpayment", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_supplierpayment_created_at"), ["created_at"], unique=False)
        batch_op.create_index(batch_op.f("ix_supplierpayment_supplier_id"), ["supplier_id"], unique=False)

    op.create_table(
        "creditnote",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("number", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("invoice_id", sa.Integer(), nullable=False),
        sa.Column("customer_id", sa.Integer(), nullable=True),
        sa.Column("customer_name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("taxable", sa.Float(), nullable=False),
        sa.Column("cgst", sa.Float(), nullable=False),
        sa.Column("sgst", sa.Float(), nullable=False),
        sa.Column("igst", sa.Float(), nullable=False),
        sa.Column("tax", sa.Float(), nullable=False),
        sa.Column("total", sa.Float(), nullable=False),
        sa.Column("refund_mode", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("refunded", sa.Float(), nullable=False),
        sa.Column("reason", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("created_by", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("created_at", sqlmodel.sql.sqltypes.UTCDateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["customer_id"],
            ["customer.id"],
        ),
        sa.ForeignKeyConstraint(
            ["invoice_id"],
            ["invoice.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("creditnote", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_creditnote_created_at"), ["created_at"], unique=False)
        batch_op.create_index(batch_op.f("ix_creditnote_invoice_id"), ["invoice_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_creditnote_number"), ["number"], unique=True)

    op.create_table(
        "supplierbill",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("supplier_id", sa.Integer(), nullable=False),
        sa.Column("po_id", sa.Integer(), nullable=True),
        sa.Column("bill_no", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("bill_date", sa.Date(), nullable=False),
        sa.Column("due_date", sa.Date(), nullable=False),
        sa.Column("amount", sa.Float(), nullable=False),
        sa.Column("paid", sa.Float(), nullable=False),
        sa.Column("notes", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("created_at", sqlmodel.sql.sqltypes.UTCDateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["po_id"],
            ["purchaseorder.id"],
        ),
        sa.ForeignKeyConstraint(
            ["supplier_id"],
            ["supplier.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("supplierbill", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_supplierbill_due_date"), ["due_date"], unique=False)
        batch_op.create_index(batch_op.f("ix_supplierbill_supplier_id"), ["supplier_id"], unique=False)

    op.create_table(
        "creditnoteline",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("note_id", sa.Integer(), nullable=False),
        sa.Column("invoice_line_id", sa.Integer(), nullable=False),
        sa.Column("product_id", sa.Integer(), nullable=False),
        sa.Column("warehouse_id", sa.Integer(), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("quantity", sa.Integer(), nullable=False),
        sa.Column("taxable", sa.Float(), nullable=False),
        sa.Column("tax", sa.Float(), nullable=False),
        sa.Column("total", sa.Float(), nullable=False),
        sa.ForeignKeyConstraint(
            ["invoice_line_id"],
            ["invoiceline.id"],
        ),
        sa.ForeignKeyConstraint(
            ["note_id"],
            ["creditnote.id"],
        ),
        sa.ForeignKeyConstraint(
            ["product_id"],
            ["product.id"],
        ),
        sa.ForeignKeyConstraint(
            ["warehouse_id"],
            ["warehouse.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("creditnoteline", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_creditnoteline_note_id"), ["note_id"], unique=False)

    with op.batch_alter_table("customer", schema=None) as batch_op:
        batch_op.add_column(sa.Column("points", sa.Integer(), nullable=False, server_default="0"))

    with op.batch_alter_table("invoice", schema=None) as batch_op:
        batch_op.add_column(sa.Column("amount_returned", sa.Float(), nullable=False, server_default="0"))
        batch_op.add_column(sa.Column("amount_refunded", sa.Float(), nullable=False, server_default="0"))
        batch_op.add_column(sa.Column("points_earned", sa.Integer(), nullable=False, server_default="0"))
        batch_op.add_column(sa.Column("client_ref", sqlmodel.sql.sqltypes.AutoString(), nullable=True))
        batch_op.create_index(batch_op.f("ix_invoice_client_ref"), ["client_ref"], unique=True)

    with op.batch_alter_table("invoiceline", schema=None) as batch_op:
        batch_op.add_column(sa.Column("returned_qty", sa.Integer(), nullable=False, server_default="0"))

    with op.batch_alter_table("supplier", schema=None) as batch_op:
        batch_op.add_column(sa.Column("credit_days", sa.Integer(), nullable=False, server_default="15"))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("supplier", schema=None) as batch_op:
        batch_op.drop_column("credit_days")

    with op.batch_alter_table("invoiceline", schema=None) as batch_op:
        batch_op.drop_column("returned_qty")

    with op.batch_alter_table("invoice", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_invoice_client_ref"))
        batch_op.drop_column("client_ref")
        batch_op.drop_column("points_earned")
        batch_op.drop_column("amount_refunded")
        batch_op.drop_column("amount_returned")

    with op.batch_alter_table("customer", schema=None) as batch_op:
        batch_op.drop_column("points")

    with op.batch_alter_table("creditnoteline", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_creditnoteline_note_id"))

    op.drop_table("creditnoteline")
    with op.batch_alter_table("supplierbill", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_supplierbill_supplier_id"))
        batch_op.drop_index(batch_op.f("ix_supplierbill_due_date"))

    op.drop_table("supplierbill")
    with op.batch_alter_table("creditnote", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_creditnote_number"))
        batch_op.drop_index(batch_op.f("ix_creditnote_invoice_id"))
        batch_op.drop_index(batch_op.f("ix_creditnote_created_at"))

    op.drop_table("creditnote")
    with op.batch_alter_table("supplierpayment", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_supplierpayment_supplier_id"))
        batch_op.drop_index(batch_op.f("ix_supplierpayment_created_at"))

    op.drop_table("supplierpayment")
    # ### end Alembic commands ###
