"""india: gst, hsn, gstin, states and upi

Revision ID: ea30328fb7b9
Revises: 9bfd7954321a
Create Date: 2026-09-24 17:45:17.003993

"""

from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "ea30328fb7b9"
down_revision: str | Sequence[str] | None = "9bfd7954321a"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("product", schema=None) as batch_op:
        batch_op.add_column(sa.Column("hsn_code", sqlmodel.sql.sqltypes.AutoString(), nullable=True))
        batch_op.add_column(sa.Column("gst_rate", sa.Float(), nullable=True))
        batch_op.add_column(sa.Column("gst_source", sqlmodel.sql.sqltypes.AutoString(), nullable=True))

    with op.batch_alter_table("supplier", schema=None) as batch_op:
        batch_op.add_column(sa.Column("gstin", sqlmodel.sql.sqltypes.AutoString(), nullable=True))
        batch_op.add_column(sa.Column("state", sqlmodel.sql.sqltypes.AutoString(), nullable=True))
        batch_op.add_column(sa.Column("upi_id", sqlmodel.sql.sqltypes.AutoString(), nullable=True))

    with op.batch_alter_table("warehouse", schema=None) as batch_op:
        batch_op.add_column(sa.Column("state", sqlmodel.sql.sqltypes.AutoString(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("warehouse", schema=None) as batch_op:
        batch_op.drop_column("state")

    with op.batch_alter_table("supplier", schema=None) as batch_op:
        batch_op.drop_column("upi_id")
        batch_op.drop_column("state")
        batch_op.drop_column("gstin")

    with op.batch_alter_table("product", schema=None) as batch_op:
        batch_op.drop_column("gst_source")
        batch_op.drop_column("gst_rate")
        batch_op.drop_column("hsn_code")

    # ### end Alembic commands ###
