/** Hindi translations, keyed by the English text used in the UI (missing keys fall back to English). */
export const HI: Record<string, string> = {
  "Daily": "रोज़ का काम",
  "Planning": "योजना",
  "AI & setup": "AI और सेटिंग",
  "Dashboard": "डैशबोर्ड",
  "Billing": "बिलिंग",
  "Stock": "स्टॉक",
  "Scan": "स्कैन",
  "Purchase orders": "खरीद ऑर्डर",
  "Insights & festivals": "जानकारी और त्योहार",
  "Stock counting": "स्टॉक गिनती",
  "AI Copilot": "AI सहायक",
  "Automation": "ऑटोमेशन",
  "Settings": "सेटिंग",
  "Sign out": "लॉग आउट",
  "Toggle theme": "थीम बदलें",
  "Open menu": "मेन्यू खोलें",
  "Close menu": "मेन्यू बंद करें",
  "Search products, pages, or ask Copilot…": "सामान खोजें या AI से पूछें…",
  "Search…": "खोजें…",
  "Public demo — sample data, resets periodically": "डेमो — नमूना डेटा, समय-समय पर रीसेट होता है",
  "Demo": "डेमो",
  "AI-native inventory": "AI वाला स्टॉक हिसाब",
  "Command palette": "कमांड",
  "Type a product, a page, or a question for Copilot…": "सामान, पेज या AI से सवाल लिखें…",
  "No matches — press Enter to ask Copilot.": "कुछ नहीं मिला — Enter दबाकर AI से पूछें।",
  "Search products and pages or ask the AI copilot": "सामान और पेज खोजें या AI से पूछें",
  "Sign in": "लॉग इन करें",
  "Password": "पासवर्ड",
  "Email": "ईमेल",
  "Inventory that plans itself — and asks before it acts.": "स्टॉक जो खुद योजना बनाए — और पूछकर ही काम करे।",
  "Multi-agent copilot": "AI सहायक",
  "Free Hermes AI (runs on your own machine) or an offline planner — with human approvals.": "मुफ़्त Hermes AI (आपके कंप्यूटर पर) या ऑफ़लाइन प्लानर — आपकी मंज़ूरी के साथ।",
  "Forecast & simulate": "अनुमान और हिसाब",
  "Holt-Winters forecasts, Monte-Carlo what-ifs, smart reorder points.": "बिक्री का अनुमान, 'अगर-तो' हिसाब, कब मँगाना है।",
  "Hooks everywhere": "ऑटोमेशन",
  "Lifecycle hooks, webhooks, autopilot, plugins and MCP.": "अपने-आप चलने वाले काम, WhatsApp/Slack सूचनाएँ।",
  "100% free to run": "100% मुफ़्त",
  "SQLite + open-source stack. No paid API required.": "कोई खर्चा नहीं, कोई पेड API नहीं।",
  "Make a bill in 3 steps, share it on WhatsApp, collect by UPI and keep track of udhaar.": "3 कदम में बिल बनाएँ, WhatsApp पर भेजें, UPI से पैसे लें और उधार का हिसाब रखें।",
  "New bill": "नया बिल",
  "All bills": "सारे बिल",
  "Khata (udhaar)": "खाता (उधार)",
  "Today's sales": "आज की बिक्री",
  "Last 7 days": "पिछले 7 दिन",
  "Udhaar to collect": "लेना बाकी (उधार)",
  "Collected by UPI (7d)": "UPI से आया (7 दिन)",
  "1 · Add items": "1 · सामान जोड़ें",
  "2 · Customer": "2 · ग्राहक",
  "3 · Payment": "3 · पेमेंट",
  "Type a name or code and press Enter · F2 jumps here · or scan the barcode": "नाम या कोड लिखकर Enter दबाएँ · या बारकोड स्कैन करें",
  "Search product… e.g. atta, sugar, ATA-101": "सामान खोजें… जैसे आटा, चीनी, ATA-101",
  "No items yet": "अभी कोई सामान नहीं",
  "Search above or scan a barcode to start the bill.": "ऊपर खोजें या बारकोड स्कैन करके बिल शुरू करें।",
  "Item": "सामान",
  "Qty": "मात्रा",
  "Price": "दाम",
  "Disc %": "छूट %",
  "Amount": "रकम",
  "Remove": "हटाएँ",
  "Prices include GST": "दाम में GST शामिल",
  "Optional — needed for udhaar or a GST bill to a business": "ज़रूरी नहीं — उधार या दुकानदार को GST बिल के लिए",
  "Add customer": "ग्राहक जोड़ें",
  "Phone": "फ़ोन",
  "Name": "नाम",
  "More (state, GSTIN, address)": "और (राज्य, GSTIN, पता)",
  "State / place of supply": "राज्य / सप्लाई की जगह",
  "Same as shop": "दुकान वाला ही",
  "Outside India": "भारत से बाहर",
  "GSTIN (business customers)": "GSTIN (दुकानदार ग्राहक)",
  "Address": "पता",
  "Cash": "नकद",
  "UPI": "UPI",
  "Card": "कार्ड",
  "Bank": "बैंक",
  "Udhaar": "उधार",
  "Split": "आधा-आधा",
  "Cash received (optional)": "कितना नकद मिला (ज़रूरी नहीं)",
  "Customer scans with GPay / PhonePe / Paytm / BHIM": "ग्राहक GPay / PhonePe / Paytm / BHIM से स्कैन करे",
  "UPI reference / UTR (optional)": "UPI रेफ़रेंस / UTR (ज़रूरी नहीं)",
  "UPI QR": "UPI QR",
  "Add your UPI ID in Settings → Business & GST to show a QR with the exact amount.": "सही रकम वाला QR दिखाने के लिए सेटिंग → दुकान की जानकारी में UPI ID डालें।",
  "Discount": "छूट",
  "Taxable value": "टैक्स योग्य रकम",
  "IGST (export, zero-rated)": "IGST (निर्यात, शून्य)",
  "Round off": "राउंड ऑफ़",
  "Total": "कुल",
  "Clear": "साफ़ करें",
  "Viewers can see bills but not create them": "व्यूअर बिल देख सकते हैं, बना नहीं सकते",
  "All": "सब",
  "Udhaar / due": "उधार / बाकी",
  "Paid": "चुकाया",
  "Cancelled": "रद्द",
  "Part paid": "आंशिक भुगतान",
  "Bill no., name or phone": "बिल नंबर, नाम या फ़ोन",
  "No bills found": "कोई बिल नहीं मिला",
  "Bill no.": "बिल नंबर",
  "Date": "तारीख",
  "Customer": "ग्राहक",
  "Mode": "तरीका",
  "Balance": "बाकी",
  "Status": "स्थिति",
  "Print A4": "A4 प्रिंट",
  "Thermal 80mm": "छोटा प्रिंट (80mm)",
  "Cancel bill": "बिल रद्द करें",
  "Receive payment": "पेमेंट लें",
  "Why cancel this bill? Stock will be returned.": "बिल क्यों रद्द कर रहे हैं? सामान स्टॉक में वापस आ जाएगा।",
  "Bill cancelled — stock returned": "बिल रद्द — सामान वापस स्टॉक में",
  "Rate": "दर",
  "Payments": "भुगतान",
  "Balance due": "बाकी रकम",
  "UTR / ref (optional)": "UTR / रेफ़ (ज़रूरी नहीं)",
  "Save": "सेव करें",
  "Khata — who owes you money": "खाता — किसका कितना बाकी है",
  "No udhaar 🎉": "कोई उधार नहीं 🎉",
  "Everyone has paid in full.": "सबने पूरे पैसे दे दिए।",
  "Bills": "बिल",
  "Since": "कब से",
  "Actions": "काम",
  "Collect": "पैसे लें",
  "Save payment": "पेमेंट सेव करें",
  "Amount received": "मिली रकम",
  "UTR / reference (optional)": "UTR / रेफ़रेंस (ज़रूरी नहीं)",
  "Sales register (CSV for CA)": "बिक्री रजिस्टर (CA के लिए CSV)",
  "Inventory value": "स्टॉक की कीमत",
  "Revenue · 30d": "कमाई · 30 दिन",
  "Active SKUs": "कुल सामान",
  "Low / critical": "कम / बहुत कम",
  "Out of stock": "खत्म",
  "Open POs": "खुले ऑर्डर",
  "vs prior 30d": "पिछले 30 दिन से",
  "losing sales now": "बिक्री छूट रही है",
  "Revenue · last 30 days": "कमाई · पिछले 30 दिन",
  "Daily sales revenue across all warehouses": "हर दिन की बिक्री",
  "Inventory health score": "स्टॉक सेहत स्कोर",
  "Availability, risk, capital, coverage & accuracy": "उपलब्धता, जोखिम, पैसा, हिसाब की सही स्थिति",
  "AI morning briefing": "AI सुबह की रिपोर्ट",
  "No briefing yet": "अभी कोई रिपोर्ट नहीं",
  "The scheduler writes one every morning.": "हर सुबह अपने-आप बनती है।",
  "Read aloud": "सुनें",
  "Alerts": "चेतावनी",
  "No open alerts.": "कोई चेतावनी नहीं।",
  "All clear": "सब ठीक",
  "Live activity": "अभी की गतिविधि",
  "Stock health": "स्टॉक की स्थिति",
  "SKUs by replenishment status": "सामान की स्थिति",
  "Stock value by category": "श्रेणी अनुसार स्टॉक कीमत",
  "Needs attention": "ध्यान दें",
  "Stockout radar": "कब खत्म होगा",
  "Days until each item runs out vs supplier lead time (next 30 days)": "हर सामान कितने दिन में खत्म होगा (अगले 30 दिन)",
  "No stockouts in the next 30 days": "अगले 30 दिन में कुछ खत्म नहीं होगा",
  "The tick marks the supplier lead time. A red gap means an order placed today still arrives after the stockout.": "लाल मतलब आज ऑर्डर देने पर भी माल खत्म होने के बाद आएगा।",
  "View all": "सब देखें",
  "Reorder now": "अभी मँगाएँ",
  "Revenue": "कमाई",
  "Units": "नग",
  "Search SKU, name, supplier…": "कोड, नाम, सप्लायर खोजें…",
  "All categories": "सारी श्रेणियाँ",
  "No products match": "कोई सामान नहीं मिला",
  "Try a different search or filter.": "दूसरी खोज या फ़िल्टर आज़माएँ।",
  "Product": "सामान",
  "Supplier": "सप्लायर",
  "On hand": "स्टॉक में",
  "Cover": "कितने दिन चलेगा",
  "Value": "कीमत",
  "SKU": "कोड",
  "Category": "श्रेणी",
  "On hand · ROP": "स्टॉक · दोबारा मँगाने का स्तर",
  "Demand/day": "रोज़ की बिक्री",
  "Healthy": "ठीक",
  "Low": "कम",
  "Critical": "बहुत कम",
  "Overstock": "ज़्यादा स्टॉक",
  "Demand forecast": "बिक्री का अनुमान",
  "Stock by warehouse": "गोदाम अनुसार स्टॉक",
  "No stock in any warehouse.": "किसी गोदाम में स्टॉक नहीं।",
  "Movements": "आना-जाना",
  "Edit": "बदलें",
  "Adjust stock": "स्टॉक बदलें",
  "Transfer": "भेजें (गोदाम से दुकान)",
  "Print label": "लेबल प्रिंट",
  "Safety stock": "सुरक्षा स्टॉक",
  "Reorder point": "दोबारा मँगाने का स्तर",
  "EOQ": "सही ऑर्डर मात्रा",
  "Lead time": "आने में समय",
  "Unit cost (₹)": "खरीद दाम (₹)",
  "Selling price (₹, before GST)": "बेचने का दाम (₹, GST से पहले)",
  "Min. order qty": "कम से कम ऑर्डर",
  "auto if empty": "खाली छोड़ें तो अपने-आप",
  "Initial quantity": "शुरुआती मात्रा",
  "Initial warehouse": "शुरुआती गोदाम",
  "Description": "विवरण",
  "GST rate (optional)": "GST दर (ज़रूरी नहीं)",
  "Let AI fill later": "AI बाद में भरेगा",
  "HSN code (optional)": "HSN कोड (ज़रूरी नहीं)",
  "e.g. 1006": "जैसे 1006",
  "Leave reorder point / safety stock empty to let the AI compute them from demand.": "दोबारा मँगाने का स्तर खाली छोड़ें — AI बिक्री से खुद निकाल लेगा।",
  "— confirm with your CA.": "— CA से पक्का कर लें।",
  "Import products from CSV": "CSV से सामान डालें",
  "Preview validates every row before anything is written.": "पहले हर लाइन जाँची जाती है, फिर सेव होती है।",
  "Preview": "पहले देखें",
  "Import": "डालें",
  "Use template": "नमूना लें",
  "…or paste CSV here": "…या CSV यहाँ चिपकाएँ",
  "Cancel": "रद्द करें",
  "Adjust ±": "घटाएँ/बढ़ाएँ",
  "Receive": "माल आया",
  "Sell": "बेचा",
  "Return": "वापसी",
  "Warehouse": "गोदाम",
  "To": "कहाँ",
  "Quantity": "मात्रा",
  "Reason": "कारण",
  "Recorded in the audit trail": "रिकॉर्ड में दर्ज होगा",
  "e.g. damaged in transit": "जैसे रास्ते में टूट गया",
  "Stock updated": "स्टॉक अपडेट हुआ",
  "Transfer completed": "भेज दिया",
  "Product label": "सामान का लेबल",
  "Scan it on the Scan page to receive, sell or count this item.": "स्कैन पेज पर इसे स्कैन करके माल आया/बेचा/गिनती करें।",
  "Scan mode": "स्कैन",
  "Point the camera at a product QR / barcode — or type a SKU. Works great on phones (install as an app).": "कैमरा बारकोड पर रखें — या USB स्कैनर / कोड लिखें। फ़ोन पर भी चलता है।",
  "Start camera": "कैमरा चालू करें",
  "Stop camera": "कैमरा बंद करें",
  "Barcode, SKU or name, e.g. ATA-105": "बारकोड, कोड या नाम, जैसे ATA-105",
  "Go": "चलें",
  "Look up": "देखें",
  "Last scan": "आखिरी स्कैन",
  "Nothing scanned yet": "अभी कुछ स्कैन नहीं हुआ",
  "Session log": "अभी तक के स्कैन",
  "Default (MAIN)": "दुकान (MAIN)",
  "Print product labels from the Inventory page to try it.": "स्टॉक पेज से लेबल प्रिंट करके आज़माएँ।",
  "Draft → approved → ordered → received. Agents draft; managers approve.": "ड्राफ्ट → मंज़ूर → ऑर्डर → माल आया। AI ड्राफ्ट बनाता है, मैनेजर मंज़ूर करता है।",
  "No purchase orders here": "यहाँ कोई ऑर्डर नहीं",
  "Generate drafts from recommendations or ask the Procurement agent.": "सुझाव से ड्राफ्ट बनाएँ या AI से पूछें।",
  "PO": "ऑर्डर",
  "Created by": "किसने बनाया",
  "Lines": "लाइनें",
  "Total (incl. GST)": "कुल (GST सहित)",
  "Expected": "कब आएगा",
  "Approve": "मंज़ूर करें",
  "Mark as ordered": "ऑर्डर हो गया",
  "Receive into stock": "माल स्टॉक में लें",
  "Unit cost": "खरीद दाम",
  "Supplier GSTIN": "सप्लायर GSTIN",
  "Value is above ₹50,000 — the supplier must generate an": "माल ₹50,000 से ज़्यादा है — सप्लायर को बनाना होगा",
  "e-way bill": "ई-वे बिल",
  "Grand total": "कुल रकम",
  "inter-state": "दूसरा राज्य",
  "Forecasts, replenishment, festivals, GST and risk — computed live from your ledger.": "बिक्री का अनुमान, क्या मँगाना है, त्योहार, GST — आपके हिसाब से।",
  "Reorder plan": "क्या मँगाना है",
  "🪔 Festival planner": "🪔 त्योहार की तैयारी",
  "Forecast & what-if": "अनुमान और 'अगर-तो'",
  "Smart markdowns": "छूट के सुझाव",
  "ABC analysis": "ABC विश्लेषण",
  "Anomalies": "गड़बड़ी",
  "Suppliers": "सप्लायर",
  "Margins": "मुनाफ़ा",
  "Replenishment plan": "मँगाने की योजना",
  "Nothing to reorder 🎉": "कुछ नहीं मँगाना 🎉",
  "Order qty": "ऑर्डर मात्रा",
  "Why": "क्यों",
  "ROP": "दोबारा मँगाने का स्तर",
  "Items at or below their reorder point · quantities = max(EOQ, gap to ROP + lead-time demand), rounded to MOQ": "जिनका स्टॉक कम है · सही मात्रा अपने-आप निकाली गई",
  "Lift": "बढ़त",
  "Extra units": "ज़्यादा नग",
  "Stock + on order": "स्टॉक + ऑर्डर में",
  "Order by": "कब तक मँगाएँ",
  "No products in the affected categories": "इन श्रेणियों में कोई सामान नहीं",
  "By GST slab": "GST स्लैब अनुसार",
  "Slab": "स्लैब",
  "Sales (taxable)": "बिक्री (टैक्स योग्य)",
  "Output tax": "बिक्री पर टैक्स",
  "Purchases": "खरीद",
  "ITC": "ITC",
  "Output tax (on sales)": "बिक्री पर टैक्स",
  "Input tax credit": "खरीद पर टैक्स क्रेडिट",
  "Output tax by slab": "स्लैब अनुसार टैक्स",
  "Last 30 days": "पिछले 30 दिन",
  "Last 90 days": "पिछले 90 दिन",
  "GSTR-3B style estimate: output tax on sales vs input tax credit (ITC) on received purchases.": "GST अनुमान: बिक्री पर टैक्स बनाम खरीद पर क्रेडिट।",
  "What-if simulator": "'अगर-तो' हिसाब",
  "No anomalies detected": "कोई गड़बड़ी नहीं",
  "Demand and write-offs look normal this week.": "इस हफ़्ते बिक्री और नुकसान सामान्य हैं।",
  "Supplier scorecards": "सप्लायर रिपोर्ट कार्ड",
  "Rating": "रेटिंग",
  "Grade": "ग्रेड",
  "On-time": "समय पर",
  "Spend": "खर्च",
  "Revenue & profit": "कमाई और मुनाफ़ा",
  "Gross profit": "कुल मुनाफ़ा",
  "Gross margin % by category": "श्रेणी अनुसार मुनाफ़ा %",
  "Smart markdown advisor": "छूट सलाहकार",
  "No excess stock worth discounting": "छूट लायक ज़्यादा स्टॉक नहीं",
  "Recommendation": "सुझाव",
  "Excess units": "ज़्यादा नग",
  "Capital tied": "फँसा पैसा",
  "Margin after": "बाद में मुनाफ़ा",
  "Business & GST": "दुकान और GST",
  "Business & GST, AI providers, integrations, catalog, people and preferences.": "दुकान, GST, AI, सामान की श्रेणियाँ, लोग और पसंद।",
  "Shop details": "दुकान की जानकारी",
  "Printed on every bill and used for the UPI QR.": "हर बिल पर छपती है और UPI QR में लगती है।",
  "Shop / business name": "दुकान का नाम",
  "Address (printed on bills)": "पता (बिल पर छपेगा)",
  "GSTIN (optional)": "GSTIN (ज़रूरी नहीं)",
  "UPI ID for payments": "पेमेंट के लिए UPI ID",
  "Bill number prefix": "बिल नंबर की शुरुआत",
  "Footer / terms": "बिल के नीचे लिखा",
  "State": "राज्य",
  "Your state is taken from the GSTIN.": "राज्य GSTIN से अपने-आप आ जाएगा।",
  "Bills show a QR with the exact amount — money goes straight to your bank, no gateway fee.": "बिल पर सही रकम वाला QR — पैसा सीधा बैंक में, कोई फ़ीस नहीं।",
  "Bills are numbered INV/26-27/00001 — a new series every financial year.": "बिल नंबर हर वित्त वर्ष नए सिरे से शुरू होते हैं।",
  "Same state as the customer → CGST + SGST, other state → IGST.": "ग्राहक उसी राज्य का → CGST + SGST, दूसरे राज्य का → IGST।",
  "Shop details saved": "दुकान की जानकारी सेव हुई",
  "GST registration": "GST रजिस्ट्रेशन",
  "I am GST-registered": "मैं GST में रजिस्टर्ड हूँ",
  "GST registered": "GST रजिस्टर्ड",
  "Optional — small shops below the GST threshold can switch it off. Nothing is lost; turn it back on any time.": "ज़रूरी नहीं — छोटी दुकानें इसे बंद कर सकती हैं। कभी भी वापस चालू करें।",
  "GST slabs (%)": "GST स्लैब (%)",
  "Reset to GST 2.0 defaults": "GST 2.0 वाले स्लैब वापस लाएँ",
  "GST settings saved": "GST सेटिंग सेव हुई",
  "HSN & GST auto-fill": "HSN और GST अपने-आप",
  "Add products without GST — the AI fills HSN code + rate from the product name later. Rates you type yourself are never overwritten.": "बिना GST के सामान डालें — AI नाम से HSN और दर भर देगा। आपकी भरी दर कभी नहीं बदलेगा।",
  "Products without GST": "बिना GST वाले सामान",
  "Filled by AI (to review)": "AI ने भरा (जाँचें)",
  "Fill missing with AI": "AI से भरें",
  "Re-check AI-filled rates": "AI वाली दरें दोबारा जाँचें",
  "Uses Hermes when it is running (free, local via Ollama), otherwise built-in rules for common Indian goods. Always confirm with your CA — the AI only suggests.": "AI सिर्फ़ सुझाव देता है — CA से पक्का करें।",
  "AI providers": "AI",
  "Hermes & MCP": "Hermes और MCP",
  "Catalog": "श्रेणियाँ और गोदाम",
  "Users": "लोग",
  "Preferences": "पसंद",
  "Warehouses": "गोदाम",
  "Categories": "श्रेणियाँ",
  "Add": "जोड़ें",
  "Code": "कोड",
  "Location": "जगह",
  "Contact": "संपर्क",
  "GSTIN · State": "GSTIN · राज्य",
  "Lead time (days)": "आने में दिन",
  "Color": "रंग",
  "Create": "बनाएँ",
  "Users & roles": "लोग और अधिकार",
  "viewer (read-only) · staff (operate) · manager (approve) · admin (everything)": "व्यूअर (सिर्फ़ देखे) · स्टाफ़ (काम करे) · मैनेजर (मंज़ूरी दे) · एडमिन (सब)",
  "Invite": "जोड़ें",
  "Invite user": "व्यक्ति जोड़ें",
  "Role": "अधिकार",
  "Temporary password": "अस्थायी पासवर्ड",
  "Create user": "व्यक्ति बनाएँ",
  "Appearance": "रंग-रूप",
  "Keyboard shortcuts": "कीबोर्ड शॉर्टकट",
  "Active": "चालू",
  "Indian numbers get +91 automatically; foreign numbers start with + and the country code.": "भारतीय नंबर में +91 अपने-आप लगेगा; विदेशी नंबर + और देश कोड से लिखें।",
  "UPI ID (optional)": "UPI ID (ज़रूरी नहीं)",
  "Purchase orders show a scan-to-pay QR for this UPI ID.": "खरीद ऑर्डर पर इस UPI ID का QR दिखेगा।",
  "Run Hermes locally for free": "Hermes AI मुफ़्त चलाएँ",
  "Reset to auto (free-first)": "अपने-आप (मुफ़्त पहले)",
  "Agent tools": "AI के औज़ार",
  "Cycle counts": "स्टॉक गिनती",
  "Count a slice of stock, compare with the system, post variances as audited adjustments.": "सामान गिनें, सिस्टम से मिलाएँ, फ़र्क सही करें।",
  "New count": "नई गिनती",
  "Count sheets": "गिनती की शीट",
  "No counts yet": "अभी कोई गिनती नहीं",
  "Start one, or ask the Auditor agent.": "एक शुरू करें, या AI से कहें।",
  "Select or create a count": "गिनती चुनें या बनाएँ",
  "Counted": "गिना",
  "Variance": "फ़र्क",
  "Blind count": "बिना देखे गिनती",
  "Progress": "प्रगति",
  "Net variance": "कुल फ़र्क",
  "Counts saved": "गिनती सेव हुई",
  "New cycle count": "नई गिनती",
  "Scope": "क्या गिनना है",
  "Everything in the warehouse": "गोदाम का सब सामान",
  "A-items first: highest value, count most often": "पहले कीमती सामान",
  "Create count sheet": "गिनती शीट बनाएँ",
  "Snapshots expected quantities for the chosen slice of stock.": "चुने सामान की मौजूदा मात्रा दर्ज करता है।",
  "Aaj ki sale": "आज की बिक्री",
  "Diwali stock": "दिवाली का स्टॉक",
  "What to reorder": "क्या मँगाना है",
  "GST this month": "इस महीने GST",
  "Morning briefing": "सुबह की रिपोर्ट",
  "What-if": "अगर-तो",
  "Investigate": "जाँच",
  "Voice input": "बोलकर लिखें",
  "Voice language": "आवाज़ की भाषा",
  "Nothing to approve": "मंज़ूरी के लिए कुछ नहीं",
  "Write actions requested by agents appear here.": "AI जो बदलाव करना चाहे, वो यहाँ आएगा।",
  "Approvals": "मंज़ूरी",
  "Trace": "रिकॉर्ड",
  "Agents": "AI सहायक",
  "Delete conversation": "बातचीत मिटाएँ",
  "Send": "भेजें",
  "Order-by = buying window start − supplier lead time. Quantities cover normal demand until the festival, the festival lift and safety stock, rounded to MOQ.": "'कब तक मँगाएँ' = सप्लायर के आने के समय से पहले। मात्रा में त्योहार की बढ़ी बिक्री शामिल है।",
  "Stop": "रोकें",
  "Stock left": "बचा स्टॉक",
  "Products": "सामान",
  "Insights": "जानकारी",
  "Copilot": "AI सहायक",
  "Cost": "खरीद दाम",
  "Nothing to reorder": "कुछ नहीं मँगाना",
  "Orders": "ऑर्डर",
  "Created": "बना",
  "on order": "ऑर्डर में",
  "Autopilot": "ऑटो-ऑर्डर",
  "Procurement autopilot": "ऑटो-ऑर्डर",
  "Last 30 days of sales": "पिछले 30 दिन की बिक्री",
  "No demand history": "बिक्री का इतिहास नहीं",
  "Gap if ordered today": "आज मँगाएँ तो कमी",
  "Run now": "अभी चलाएँ",
  "Test": "जाँचें",
  "Webhooks": "वेबहुक",
  "Scheduled jobs": "तय काम",
  "Audit trail": "रिकॉर्ड",
  "Default": "डिफ़ॉल्ट",
  "Increase": "बढ़ाएँ",
  "Decrease": "घटाएँ",
  "Action": "काम",
  "Class A items": "A श्रेणी (कीमती)",
  "Class B items": "B श्रेणी",
  "Class C items": "C श्रेणी",
  "critical": "गंभीर",
  "warning": "चेतावनी",
  "info": "जानकारी",
  "current": "अभी",
  "Add product": "सामान जोड़ें",
  "Agents use live tools. Stock changes, transfers and PO status changes always wait for a manager's approval.": "AI असली डेटा देखता है। स्टॉक बदलने जैसे काम हमेशा मैनेजर की मंज़ूरी के बाद ही होते हैं।",
  "Ask Copilot": "AI से पूछें",
  "Cancel PO": "ऑर्डर रद्द करें",
  "Export": "डाउनलोड",
  "Generate from recommendations": "सुझाव से ऑर्डर बनाएँ",
  "Import CSV": "CSV डालें",
  "Investigate with Auditor →": "AI से जाँच करवाएँ →",
  "Label": "लेबल",
  "New chat": "नई बातचीत",
  "Post variances": "फ़र्क सही करें",
  "Print": "प्रिंट",
  "Regenerate": "दोबारा बनाएँ",
  "Remind": "याद दिलाएँ",
  "Run simulation": "हिसाब लगाएँ",
  "Save bill": "बिल सेव करें",
  "Send on WhatsApp": "WhatsApp पर भेजें",
  "Suggest with AI": "AI से सुझाव",
  "WhatsApp": "WhatsApp",
  "Language": "भाषा",
  "Help & tutorial": "मदद और ट्यूटोरियल",
  "Watch video": "वीडियो देखें",
  "Next": "आगे",
  "Back": "पीछे",
  "Skip": "छोड़ें",
  "Start using the app": "ऐप शुरू करें",
  "Step {n} of {total}": "कदम {n} / {total}",
  "Welcome to {shop}": "{shop} में आपका स्वागत है",
  "Your shop's billing, stock, udhaar and AI helper — in one simple app.": "बिल, स्टॉक, उधार और AI सहायक — एक आसान ऐप में।",
  "Choose your language": "अपनी भाषा चुनें",
  "You can change it any time from the top bar.": "ऊपर की पट्टी से कभी भी बदल सकते हैं।",
  "Make a bill": "बिल बनाएँ",
  "Billing → type the item name or scan its barcode → choose Cash / UPI / Udhaar → Save bill. Print it or send it on WhatsApp.": "बिलिंग → सामान का नाम लिखें या बारकोड स्कैन करें → नकद / UPI / उधार चुनें → बिल सेव करें। प्रिंट करें या WhatsApp पर भेजें।",
  "Scan barcodes": "बारकोड स्कैन करें",
  "Use a USB barcode scanner (just scan — it types the code), or tap Scan to use the phone camera.": "USB बारकोड स्कैनर लगाएँ (बस स्कैन करें) या फ़ोन कैमरे के लिए 'स्कैन' दबाएँ।",
  "Udhaar khata": "उधार खाता",
  "Billing → Khata shows who owes you money. Send a WhatsApp reminder or collect with one tap.": "बिलिंग → खाता में दिखता है किसका कितना बाकी है। एक टैप में WhatsApp याद दिलाएँ या पैसे लें।",
  "Stock & expiry": "स्टॉक और एक्सपायरी",
  "The dashboard warns you when stock is low or items are about to expire. Stock shows every item with its barcode and expiry.": "स्टॉक कम होने या सामान एक्सपायर होने से पहले डैशबोर्ड बताता है।",
  "Festivals & AI": "त्योहार और AI",
  "Festivals for your state show what to stock and by when. Ask the AI in Hindi: \"aaj ki sale?\", \"kiska udhaar baaki hai?\"": "आपके राज्य के त्योहार बताते हैं क्या और कब मँगाना है। AI से हिंदी में पूछें: \"आज की सेल?\", \"किसका उधार बाकी है?\"",
  "Day end: Aaj ka hisaab": "दिन का अंत: आज का हिसाब",
  "At closing time open Billing → Aaj ka hisaab: total sale, cash in the galla, UPI, udhaar. Print or WhatsApp it.": "दुकान बंद करते समय बिलिंग → आज का हिसाब: कुल बिक्री, गल्ले में नकद, UPI, उधार। प्रिंट या WhatsApp करें।",
  "Aaj ka hisaab": "आज का हिसाब",
  "Day-end closing": "दिन का हिसाब",
  "Bills today": "आज के बिल",
  "Sale": "बिक्री",
  "Cash in galla": "गल्ले में नकद",
  "Udhaar given": "उधार दिया",
  "Udhaar collected": "उधार वापस आया",
  "Received by mode": "किस तरीके से आया",
  "Top items today": "आज सबसे ज़्यादा बिका",
  "No bills on this day": "इस दिन कोई बिल नहीं",
  "Expiring soon": "जल्दी एक्सपायर",
  "Expired": "एक्सपायर हो गया",
  "days left": "दिन बाकी",
  "Nothing expiring in the next 15 days": "अगले 15 दिन में कुछ एक्सपायर नहीं",
  "Sell these first or return them to the supplier": "इन्हें पहले बेचें या सप्लायर को लौटाएँ",
  "Expiry": "एक्सपायरी",
  "Expiry date": "एक्सपायरी तारीख",
  "Barcode": "बारकोड",
  "Unit": "इकाई",
  "Scan barcode": "बारकोड स्कैन करें",
  "Barcode scanned": "बारकोड स्कैन हुआ",
  "No product with this code — add it?": "इस कोड का कोई सामान नहीं — जोड़ें?",
  "Shop": "दुकान",
  "Region": "क्षेत्र",
  "Festivals for {state}": "{state} के त्योहार",
  "Festivals shown for your shop's state — change it in Settings → Shop details.": "आपकी दुकान के राज्य के त्योहार — सेटिंग → दुकान की जानकारी में बदलें।",
  "Regional": "क्षेत्रीय",
  "Print hisaab": "हिसाब प्रिंट करें",
  "Share on WhatsApp": "WhatsApp पर भेजें",
  "Tutorial video": "ट्यूटोरियल वीडियो",
  "Show tutorial again": "ट्यूटोरियल दोबारा देखें",
  "Returning customer": "पुराने ग्राहक",
  "udhaar baaki": "उधार बाकी",
  "no dues": "कोई बाकी नहीं",
  "Return change:": "वापस दें:",
  "Show UPI QR for": "UPI QR दिखाएँ",
  "will go on the customer's khata.": "ग्राहक के खाते में जाएगा।",
  "The full amount goes on the customer's khata (udhaar). You can send a WhatsApp reminder later.": "पूरी रकम ग्राहक के खाते (उधार) में जाएगी। बाद में WhatsApp पर याद दिला सकते हैं।",
  "Add the customer's name and phone for udhaar.": "उधार के लिए ग्राहक का नाम और फ़ोन डालें।",
  "in stock": "स्टॉक में",
  "only {n} in stock": "सिर्फ़ {n} स्टॉक में",
  "Good morning": "सुप्रभात",
  "Good afternoon": "नमस्ते",
  "Good evening": "शुभ संध्या",
  "here's what needs your attention.": "आज ध्यान देने वाली बातें।",
  "Draft reorder POs": "मँगाने के ऑर्डर बनाएँ",
  "units": "नग",
  "overstocked": "ज़्यादा स्टॉक",
  "need reorder": "मँगाने हैं",
  "open alerts": "चेतावनियाँ",
  "Today: {amount} from {n} bills": "आज: {n} बिल से {amount}",
  "udhaar to collect from {n} customer(s)": "उधार लेना है {n} ग्राहकों से",
  "No udhaar pending": "कोई उधार बाकी नहीं",
  "7 days": "7 दिन",
  "in {n} days": "{n} दिन में",
  "{n} products need extra stock (~{amount} extra sales)": "{n} सामान ज़्यादा मँगाने हैं (~{amount} ज़्यादा बिक्री)",
  "first order by": "पहला ऑर्डर",
  "Stock already covers the expected festival demand.": "त्योहार के लिए स्टॉक पूरा है।",
  "Prices include GST (MRP style) — switch off for B2B bills": "दाम में GST शामिल (MRP) — दुकानदार के बिल के लिए बंद करें",
  "bills": "बिल",
  "avg": "औसत",
  "customer(s)": "ग्राहक",
  "Filled by AI — please check": "AI ने भरा — जाँच लें",
  "Leave blank: AI fills it from the name": "खाली छोड़ें: AI नाम से भर देगा",
}
